export enum PeopleEnum {
  YuthVorachattarn = 'yuthVorachattarn',
  VithitLeenutaphong = 'vithitLeenutaphong',
  VilaiChattanrassamee = 'vilaiChattanrassamee',
  WichitRattanasirivilai = 'wichitRattanasirivilai',
  SuchinRattanasirivilai = 'suchinRattanasirivilai',
  AnggoonSrisunthorn = 'anggoonSrisunthorn',
  ChairatChongyangyuenvong = 'chairatChongyangyuenvong',
  SauwakunKaruchit = 'sauwakunKaruchit',
  BanchaiKaruchit = 'banchaiKaruchit',
  KittikhunLochaya = 'kittikhunLochaya',
  MinrawiPhodee = 'minrawiPhodee',
  BunditRungsimanon = 'bunditRungsimanon',
  RoongrojWhangteeranon = 'roongrojWhangteeranon',
}
