export enum StrapiRevalidateTag {
  PressRelease = 'article:press-release-list',
  CompanyNews = 'article:company-news-list',
  Article = 'article:article-list',
  SocialResponsibility = 'article:social-responsibility-list',
  Person = 'person:person-list',
  Committee = 'committee:committee-list',
  PopupBanner = 'popup-banner:popup-banner-list',
  EService = 'e-service:e-service-list',
  ShareHolderMeeting = 'shareholder-meeting:shareholder-meeting-list',
  FinancialInfo = 'financial-info:financial-info-list',
  AnnualReport = 'annual-report:annual-report-list',
  OperatingResult = 'operating-result:operating-result-list',
  PublishedDocument = 'published-document:published-document-list',
  CorporateGovernance = 'corporate-governance:corporate-governance',
  Policy = 'policy:policy-list',
}
