// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface NoName {
  component: "เอกสารแต่ละไตรมาส";
  _uid: string;
  [k: string]: unknown;
}

export interface DownloadLink {
  Title: string;
  linkURL: string;
  component: "downloadLink";
  _uid: string;
  [k: string]: unknown;
}

export interface EventNewsDetailCard {
  newsImageCover: StoryblokAsset;
  newsTitle: string;
  newsDate: string;
  newsDescription: StoryblokRichtext;
  metaTitle: string;
  metaDescription: string;
  metaImage: StoryblokAsset;
  component: "eventNewsDetailCard";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Group {
  heading?: string;
  tab?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "group";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface PerformanceQuarterForms {
  heading?: string;
  quarter1Text?: string;
  quarter1File?: StoryblokAsset;
  quarter2Text?: string;
  quarter2File?: string;
  component: "performanceQuarterForms";
  _uid: string;
  [k: string]: unknown;
}

export interface PerformanceReportPage {
  Title?: string;
  performanceBoxYearContainer?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "performance-report-page";
  _uid: string;
  [k: string]: unknown;
}

export interface Row {
  heading?: string;
  youtubeUrl?: string;
  file?: StoryblokAsset;
  component: "row";
  _uid: string;
  [k: string]: unknown;
}

export interface RowBlock {
  title?: string;
  youtubeUrl?: string;
  file?: StoryblokAsset;
  component: "RowBlock";
  _uid: string;
  [k: string]: unknown;
}

export interface ShowOneImage {
  ImageA: StoryblokAsset;
  component: "showOneImage";
  _uid: string;
  [k: string]: unknown;
}

export interface ShowThreeImage {
  ImageA: StoryblokAsset;
  ImageB: StoryblokAsset;
  ImageC: StoryblokAsset;
  component: "showThreeImage";
  _uid: string;
  [k: string]: unknown;
}

export interface ShowTwoImage {
  ImageA: StoryblokAsset;
  ImageB: StoryblokAsset;
  component: "showTwoImage";
  _uid: string;
  [k: string]: unknown;
}

export interface Tab {
  heading?: string;
  row?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "tab";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface ToggleBlock {
  heading?: string;
  RowBlock?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "ToggleBlock";
  _uid: string;
  [k: string]: unknown;
}

export interface ToggleContainerPage {
  ToggleBlock?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "ToggleContainerPage";
  _uid: string;
  [k: string]: unknown;
}

export interface TogglePage {
  group?: (
    | DownloadLink
    | EventNewsDetailCard
    | Feature
    | Grid
    | Group
    | Page
    | PerformanceQuarterForms
    | PerformanceReportPage
    | Row
    | RowBlock
    | ShowOneImage
    | ShowThreeImage
    | ShowTwoImage
    | Tab
    | Teaser
    | ToggleBlock
    | ToggleContainerPage
    | TogglePage
  )[];
  component: "togglePage";
  _uid: string;
  [k: string]: unknown;
}
