import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, unstable_setRequestLocale } from 'next-intl/server'
import { GoogleTagManager } from '@next/third-parties/google'

import 'swiper/css'
import 'swiper/css/pagination'
import './globals.css'

import { LocaleEnum } from '@/enums/LocaleEnum'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import StoryblokProvider from '@/components/StoryBokProvider'

import CookieConsentFloatingBar from '@/components/CookieConsentFloatingBar/CookieConsentFloatingBar'
import { ScrollVisibleProvider } from '@/context/ScrollVisibleContext'

import '@/libs/storyblok/init'
import { BannerPopup } from '@/components/BannerPopup/BannerPopup'

export const revalidate = 604800 //7 days

export const metadata: Metadata = {
  title: 'เทคโนโลยี - Sahathai Terminal',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: LocaleEnum }
}>) {
  unstable_setRequestLocale(locale)
  const messages = await getMessages()

  return (
    <StoryblokProvider>
      <html lang={locale}>
        <head>
          <link rel='icon' href='/favicon.ico' sizes='any' />
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1.0, user-scalable=no'
          />
        </head>
        <body>
          <NextIntlClientProvider messages={messages}>
            <ScrollVisibleProvider>
              <Header />

              {children}
              <Footer />
              <BannerPopup />
              <ToastContainer />
              <GoogleTagManager gtmId={process.env.GTM_STAGING!} />
              <CookieConsentFloatingBar />
            </ScrollVisibleProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </StoryblokProvider>
  )
}
