import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, unstable_setRequestLocale } from 'next-intl/server'

import 'swiper/css'
import 'swiper/css/pagination'
import './globals.css'
import { LocaleEnum } from '@/enums/LocaleEnum'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import StoryblokProvider from '@/components/StoryBokProvider'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'

export const metadata: Metadata = {
  title: 'เทคโนโลยี - Sahathai Terminal',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: LocaleEnum }
}>) {
  unstable_setRequestLocale(locale)
  const messages = await getMessages()

  // storyblokInit({
  //   accessToken: 'H1wfrTArHm3VE441H8WQ5wtt',
  //   use: [apiPlugin],
  // })

  return (
    <html lang={locale}>
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, user-scalable=no'
        />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          <Footer />
          <ToastContainer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
