import type { Metadata } from 'next'
import { Kanit, Sarabun } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import 'swiper/css'
import 'swiper/css/pagination'
import './globals.css'
import { LocaleEnum } from '@/enums/LocaleEnum'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

const sarabun = Sarabun({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['thai'],
  variable: '--font-sarabun',
})
const kanit = Kanit({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['thai'],
  variable: '--font-kanit',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: LocaleEnum }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale} className={`${sarabun.variable} ${kanit.variable}`}>
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, user-scalable=no'
        />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header locale={locale} />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
